### ISSUE TITLE
Technical > Add website to github

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#112]
- [x] Create a repository for the CPR website under the CPR organisation on github
- [x] Integrate Netlify CMS into website
- [x] Set up CI/CD with CMS and Netlify hosting

**Comment by eurolife** [comment]
All steps above have been completed.

**Comment by eurolife** [comment]
Issue moved to [climatepolicyradar/website #33](https://github.com/climatepolicyradar/website/issues/33) via [**ZenHub**](https://www.zenhub.com/)
