### ISSUE TITLE
Research > Plan for improved semantic search

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#113]
Put together a research plan for improvements the quality of semantic search results. This should cover:

- Research objectives
- Research tasks
- Evaluation of results

Also look at search frameworks in big companies

**Comment by kdutia** [comment]
See [this notion page](https://www.notion.so/climatepolicyradar/Semantic-search-ab95112c1912496f82c8df7b576f8d27) for the WIP plan

**Comment by kdutia** [comment]
@chrisaballard I've just raised #116 from this. Happy to close, and we can plan the next steps for the research work on Monday?
