### ISSUE TITLE
A researcher can submit a new policy to the CPR database

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#122]
Build a simple form to allow a user to submit a new policy into the CPR database.
The user should enter the following information:

- Policy source (string identifier)
- Policy title (text field)
- Source policy description (multiline text field)
- Policy date (date selector)
- Country name (drop down of country names with autocomplete - a single value)
- List of languages contained in the policy text (multi-select with autocomplete)
- Document type (drop down - values to be specified)
- Attached a single or multiple documents either by:
   - specifying the url where the document can be found
   - selecting a local file
   - (it should be possible to choose multiple documents)

Tasks:
- [ ] @marcusodavies and danny to define the predefined values for Document Type - details will be added to this task. The `document_type` field in processed_policies.csv contains CCLW's list of these.

**Comment by kdutia** [comment]
working version of information requirements for policy submission: https://www.notion.so/climatepolicyradar/Action-submission-API-design-585004266c064fa8b0d5cb9e8bbba6ce

**Comment by kdutia** [comment]
Issue moved to [climatepolicyradar/navigator #12](https://github.com/climatepolicyradar/navigator/issues/12) via [**ZenHub**](https://www.zenhub.com/)
