### ISSUE TITLE
API > Submit a new policy

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#136]
Create a REST api that a new policy can be submitted to. This should support a POST request.

- [x] Define structure of POST request
- [x] Create API
  - [x] document upload API
  - [x] action submission API
- [ ] Write tests (including mocking s3)
- [ ] Document API using OPENAPI json - this should be visible using the fastapi documentation support
- [ ] Return a response indicating that policy has been submitted, or an error has occurred

**Comment by kdutia** [comment]
@chrisaballard @eurolife here's a draft of the POST request structure (first point above) for your review https://www.notion.so/climatepolicyradar/Policy-submission-API-design-585004266c064fa8b0d5cb9e8bbba6ce

**Comment by kdutia** [comment]
Issue moved to [climatepolicyradar/navigator #11](https://github.com/climatepolicyradar/navigator/issues/11) via [**ZenHub**](https://www.zenhub.com/)
