### ISSUE TITLE
Create country and language mappings

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#138]
Create two files defining mapping between code and name for country and languages which can be selected by the user in the app. These files will be imported into the database chosen in #140

**Comment by kdutia** [comment]
Downloaded language mappings and ISO codes using the `ISO-639-3` mapping from the official source:  https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab. 

These are the [set of ISO codes which aim to cover all languages](https://en.wikipedia.org/wiki/ISO_639-3). They should be suitable for us, unless we decide to filter down the list for users' ease.

**Comment by kdutia** [comment]
@chrisaballard I think this task is complete and the rest will be covered by #140 - as long as we're happy with using the existing geographies data and the languages data in my above comment.
