### ISSUE TITLE
Automatically run unit tests

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#141]
- Decide what packages we'll use for creating and maintaining unit tests
- Struture for writing tests in codebase
- Where and how to automate running of them (jenkins / gh actions)

**Comment by chrisaballard** [comment]
I'm reviewing structure of open source projects using similar tech stack to us (python + react/vue). Where I come across how they're structuring unit tests, I'll add comments to #142

**Comment by kdutia** [comment]
@chrisaballard  i'd just started based on your work, so will pause for now and see what you come up with! 

*so far*

**Python:** 
* popular open source repos such as spaCy and rubrix use `pytest`. Rubrix uses `pytest-cov` for code coverage.
* Rubrix has code at `./src/rubrix` and tests at `./tests`. spaCy has code at `./spacy` and tests at `./spacy/tests`. The latter seems better for us, but depends on how easy tests are to run using pytest.

**Comment by chrisaballard** [comment]
@kdutia don't pause this, feel free to continue to explore the options and make a recommendation based on what you find. I'm focused more on the structure in #142, will add my thoughts on tests here instead where I come across good examples. See you've already looked at Rubrix which was a starting point for me too.

**Comment by kdutia** [comment]
@eurolife happy to take your lead on testing frameworks for frontends/next.js. Did you say you'd used [Cypress](https://www.cypress.io/) or jest?

**Comment by kdutia** [comment]
## Automatically running tests

Github actions allows you to [run commands in a virtual environment to e.g. lint and test](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python). These can be run when someone commits to the `master` branch or opens a pull request to the `master` branch. Secrets can be saved at a repository level.

Github actions would also allow us to [continuously deploy](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service), or even publish a new version of a package to `pypi` or `npm` when a release is created. 

@chrisaballard interested in your thoughts :) 
Github actions usage is [free for public repos, and limited to 2,000 minutes per month for private repos](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

Other alternatives are Jenkins, Travis or CircleCI. We'd need to self-host Jenkins or Travis.

I think we should start with Github actions as it seems to be able to do what we need, has a large community of users, and doesn't involve the complexity of learning or setting up another platform.

**Comment by kdutia** [comment]
Running backend tests takes ~3m20s, the vast majority of which is build time for docker-compose. At the moment I'm just using the env variables in `.env.example` - in future we may want to consider a store for environment variables for different environments, and pull the ones for our test environment for this purpose.

**Comment by kdutia** [comment]
Tests are running for backend and frontend separately. However, frontend tests currently just start the frontend using `npm ci && npm run build`, rather than using the whole stack. 

Using cypress with docker or docker-compose is proving tricky. Need to evaluate with @chrisaballard whether we want frontend tests to run on a frontend that's connected to a local (i.e. on the GH actions server) stack, or a test environment somewhere else in the cloud. This will dictate whether to get cypress working with docker-compose.

**Comment by chrisaballard** [comment]
Reviewed - tested frontend and backend tests work locally. I could get the backend pytest tests working fine, but for some reason had a problem with the backend tests - doesn't seem to connect to the cypress docker container. However, both backend and frontend tests run fine as the github action.

I've made a small tweak to add a status batch to the readme. I did this to test the action was working ok, but also because it could be super helpful!

Some suggested improvements we could make later:

    One improvement we could make would be outputing the pytest results in junit format which would then allow us to add a test status report displayable in github so that interpreting test results is easier.
    Adding pytest-coverage so that we can view the coverage of unit tests - will help us to monitor how well tested our codebase is. Will add some issues to the backlog for these.

Overall though, this is all good and working as expected :)
