### ISSUE TITLE
Website changes

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#143]
List of tasks:
notion://www.notion.so/climatepolicyradar/Pumpkin-pie-3876ab0ef0b94bf7b695abfdc14bd32b#6e34d8857aeb40538542706790113cf1

- [x] Change name of "Newsroom" link to -----
- [x] Display all text in values section instead of clicking "+" button to display it. Change layout of values so that we have a single row of values. Clicking on value displays the text for that value. 
- [ ] Provide a few different choices of icons for each concept.
- [x] Organise advisory members in alpha order of surname
- [x] "Our Funders" and "Our Partners" logos should be contained in a box with rounded corners
- [x] Subak logo is not the best - could they give us a logo with a background?
- [x] Make sure Quadrature and Subak logos are the same size
- [x] Same with the logos in the partners section - crop out vertical white space
- [x] Add horizontal line to separate sitemap from the rest of the page
- [x] Review smithfield page - are these all done?
- [x] Contact > "Speak soon" should have an exclamation mark
- [x] Contact > @michal-nachmany to review drop down options
- [x] Website > Georgia copy editor to review website text
- [ ] What are we doing with the media page links to Michal on Daily Climate Show, etc? Do they belong on Media page?
- [x] Make sure date automatically formats properly when adding a blog entry in the CMS
- [x] Order of sub-menu items under Who We Are to match order they appear on page

**Comment by michal-nachmany** [comment]
See below my comments in blue. Also attaching Georgie's edits to text (note she was looking at existing website rather than staging but edits are edits). Let me know if something is unclear.

Dr Michal Nachmany | Founder & CEO, Climate Policy Radar CIC | +44 (0) 777 575 1906 | She/her | Twitter: @nachmanymichal /  @climatepolradar | https://climatepolicyradar.org ( https://climatepolicyradar.org/ )

On Tue, Dec 07, 2021 at 15:26:48, Chris Ballard < ***@***.*** > wrote:

> 
> 
> 
> 
> 
> List of tasks:
> 
> notion://www.notion.so/climatepolicyradar/Pumpkin-pie-3876ab0ef0b94bf7b695abfdc14bd32b#6e34d8857aeb40538542706790113cf1
> 
> 
> 
> 
> 
> 
> 
> 
> * Change name of "Newsroom" link to ----- News and Commentaries
> 
> * Display all text in values section instead of clicking "+" button to
> display it. Change layout of values so that we have a single row of
> values. Clicking on value displays the text for that value. Provide a few
> different choices of icons for each concept.
> 
> * Organise advisory members in alpha order of surname
> 
> * "Our Funders" and "Our Partners" logos should be contained in a box with
> rounded corners
> 
> * Subak logo is not the best - could they give us a logo with a
> background?
> 
> * Make sure Quadrature and Subak logos are the same size
> 
> * Same with the logos in the partners section - crop out vertical white
> space
> 
> * Add horizontal line to separate sitemap from the rest of the page
> 
> * Review smithfield page - are these all done?
> 
> * Contact > "Speak soon" should have an exclamation mark
> 
> * Contact > @ michal-nachmany ( https://github.com/michal-nachmany ) to
> review drop down options
> 
> 
> 
> 
> 

collaborating on research

contributing to open source code

working at Climate Policy Radar

offering you a service/product

Something else

**Comment by eurolife** [comment]
All above is done and ready to review, and also awaiting decisions on the media page items and the Values icons.
