### ISSUE TITLE
Score query embedding similarity with passage embeddings at query time

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#29]
This task is to change the API to generate a query embedding and then score similarity of the query with dense passage vectors.

- [x] Encode query at query time using sentence embedding model
- [x] Update opensearch query to score based on embedding similarity
- [x] Return search results in the api based on embedding scores

**Comment by kdutia** [comment]
work done on branch `feat-115-vector-database`

**Comment by chrisaballard** [comment]
Merged into dev, and appears to all be working ok.
