### ISSUE TITLE
Add hard-coded, non-functional filter buttons

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/policy-search#51]
Filters are grouped as follows, using different headers. Each header is represented by a different icon.

## Country
- Geography *(functional)*
- Income group
- Political groupings

## Document level
- Document type
- Year *(functional)*
- Language
- Type (law, policy, action plan, NDC)

## Passage level
- Sector *(functional)*
- Instrument *(functional)*
- Targets
- Technologies
- Core needs
- Enablers

[Annotated screenshots](https://docs.google.com/presentation/d/1RqviIpZkjbwHgXnaulJZyCSP9ycxE8UJp6L4hySFJ9k/edit#slide=id.p).

**Comment by eurolife** [comment]
UI is completed and ready to review.
