### ISSUE TITLE
Issue with query response time

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#72]
Investigate issues with long query response times that could cause issues during presentations.

It seems that the query aggregation is causing a significant overhead. Investigate whether:

1. Its possible to optimise the aggregation that opensearch is running, or
2. Whether the aggregation can/should be performed outside of opensearch. However this will involve returning a larger number pages per query.

```json
"aggs": {
    "top_docs": {
            "terms": {
                    "field": "policy_id",
                    "order": {"top_hit": "desc"}
            },
            "aggs": {
                    "top_passage_hits": {
                            "top_hits": {
                                    "_source": {"excludes": ["text.embedding"]},
                                    "size": 10
                            }
                    },
                    "top_hit": {"max": {"script": {"source": "_score"}}}
            }
    }
}
```

**Comment by kdutia** [comment]
Added a [sampler](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-sampler-aggregation.html) to limit the number of docs that are considered to be aggregated
