### ISSUE TITLE
Inconsistent search results when user pauses during entry of search expression

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#74]
When the user types a query, the search is carried out before the user has finished typing. This results in inconsistent search results being displayed.

For example, when entering the search expression `tax on domestic flights`, if the user pauses midway through entering the search expression, a search is performed whilst the user is still entering their search query. This provides search results for an incomplete expression.

After the user has finished entering their search expression, the title `Results for ...` is updated to display their full search expression, but the search results are not refreshed.

To avoid inconsistent results, the search should not be carried out until the user presses <Enter> or clicks a <Search> button.

**Comment by eurolife** [comment]
The search is now only executed when the user presses the Enter key.
