### ISSUE TITLE
Test Adobe PDF Embed API

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#87]
Test the [Adobe PDF Embed JavaScript API](https://www.adobe.io/apis/documentcloud/dcsdk/pdf-embed.html) to see how we can use it and embed pdf display within the front end. In particular:

- how to embed pdf display in the front end
- what interaction we could use between the front end and the pdf - for example:
  - directly displaying the passage
  - displaying text and highlighting the corresponding section in the pdf side by side.
  - selection of text spans or passages for labelling
- configuring the display to show/hide ui elements in the pdf viewer

**Comment by chrisaballard** [comment]
The objective of this task is to evaluate improved ways of displaying policy pdf documents which is integrated inside the front end, and which allow for interaction between the front end itself and the pdf document.

The Adobe embed API is one possible way to do this, and is a logical place to start.

In terms of functionality that we should evaluate, I think the following will be important characteristics:

- Able to link a passage displayed in the front end to the corresponding location of that passage in the pdf. i.e. clicking on the passage displays the passage selected in the pdf.
- In the near future, we will most likely have an "outline view" of the policy showing the key sections and titles. Clicking on a section title should allow the user to display the corresponding section in the pdf.
- Obtaining labelled data from users is going to be importantant. It will be interesting to see whether this could be done inside the pdf document, or whether it is best done outside. The benefit of in the pdf would be that the user gets a better sense of where in the document they are. This labelling would include:
  - Highlighting a complete passage or section and selecting from a category for that passage or section
  - Highlighting individual words in a passage and selecting from a category for those words
  - Connecting together related sections - i.e. this is the sector that a particular instrument applies to.

**Comment by eurolife** [comment]
In reviewing the embed API, I focused on those of the characteristics noted above which would be easiest to implement, namely, highlighting a passage and labelling it from a choice or choices of categories. 

I pulled from the available sample code the ability to highlight a section and add notes or comments to the selection or anywhere on the page. 

From this, I adapted it and put together a very simple limited demo which just allows users to select a passage of text and assign labels to it from a short list of categories.

- User can highlight a section of text, then choose one or more categories to label it with.
- User can update (not implemented) or delete the highlight/labels.

I can demonstrate the above in the sprint demo.

I'd also like to show what data is available within an annotation once it's created.

At this time, I am not able to see an obvious way of breaking the document up into an outline form or being able to link to a specific passage from an outline. However, if we look at the annotation data available, there is an id and some bounding box values. If it's at all possible to map bounding box values to an outline section that could be generated with the extractor (I don't know what its capabilities are) then perhaps we could implement this with a little extra effort. Would require further research.

**Comment by eurolife** [comment]
https://user-images.githubusercontent.com/8472119/140973439-e4dbadb2-8f76-4e7a-81eb-2aa31d57c29c.mp4

Demo for labelling text passages

Annotation schema: https://opensource.adobe.com/pdfembed-sdk-docs/howtos_comments.html#annotation-schema

All docs: https://www.adobe.io/apis/documentcloud/dcsdk/docs.html?view=view

Working code samples: https://www.adobe.com/go/pdfembedapi_samples
